const iconPaths={library:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/><circle cx="9" cy="7" r="4"/>',sparkles:'<path d="m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3ZM20 2v4M18 4h4"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',sliders:'<path d="M4 7h8M16 7h4M4 17h3M11 17h9"/><circle cx="14" cy="7" r="2"/><circle cx="9" cy="17" r="2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',play:'<path d="m8 4 12 8-12 8Z" fill="currentColor" stroke-width="0"/>',pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',previous:'<path d="M5 5v14m14-14L7 12l12 7Z" fill="currentColor"/>',next:'<path d="M19 5v14M5 5l12 7-12 7Z" fill="currentColor"/>',volume:'<path d="m11 4-6 5H2v6h3l6 5V4ZM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',muted:'<path d="m11 4-6 5H2v6h3l6 5V4Zm5 5 6 6m0-6-6 6"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3"/><rect x="3" y="12" width="4" height="9" rx="2"/><rect x="17" y="12" width="4" height="9" rx="2"/>'};

Object.assign(iconPaths,{ball:'<circle cx="12" cy="12" r="9"/><path d="m12 7 5 3-2 6H9l-2-6 5-3ZM12 3v4M3 10l4 1m14-1-4 1M7 20l2-4m8 4-2-4"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',trophy:'<path d="M8 3h8v5a4 4 0 0 1-8 0V3Zm0 2H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 0v6m-4 3h8m-6-3h4"/>',chart:'<path d="M3 3v18h18M7 14l4-5 4 3 5-7"/>',field:'<rect x="3" y="2" width="18" height="20" rx="1"/><path d="M3 12h18M8 2v5h8V2M8 22v-5h8v5"/><circle cx="12" cy="12" r="3"/>'});
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name]||iconPaths.ball}</svg>`;
const $=s=>document.querySelector(s);
const fillIcons=(root=document)=>root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const clubs=[['Barcelona','BC','Barcelona, Spain','Virtual Champions'],['Dortmund','DO','Dortmund, Germany','Virtual Champions'],['Liverpool','LI','Liverpool, England','Virtual Premier'],['Arsenal','AR','London, England','Virtual Premier'],['Bayern','BY','Munich, Germany','Virtual Bundesliga'],['Leipzig','LP','Leipzig, Germany','Virtual Bundesliga'],['Juventus','JU','Turin, Italy','Virtual Serie A'],['Milan','MI','Milan, Italy','Virtual Serie A'],['Real Madrid','RM','Madrid, Spain','Virtual Champions'],['Atlético','AT','Madrid, Spain','Virtual Champions'],['Man. City','MC','Manchester, England','Virtual Premier'],['Man. United','MU','Manchester, England','Virtual Premier'],['Leverkusen','LV','Leverkusen, Germany','Virtual Bundesliga'],['Wolfsburg','WO','Wolfsburg, Germany','Virtual Bundesliga'],['Inter','IN','Milan, Italy','Virtual Serie A'],['Napoli','NA','Naples, Italy','Virtual Serie A']].map((c,id)=>({id,name:c[0],short:c[1],location:c[2],league:c[3],w:8-id%5,d:id%3,l:10-(8-id%5)-id%3,gf:24-id%10,ga:8+id%7,pts:(8-id%5)*3+id%3}));
const games=[
 {id:0,home:0,away:1,score:[2,1],minute:68,status:'Live',league:'Virtual Champions',group:'A',round:'Quarter-final',comment:'Silva scores from close range.',events:[[18,'home','Costa'],[42,'away','Weber'],[68,'home','Silva']],possession:58},
 {id:1,home:2,away:3,score:[1,1],minute:54,status:'Live',league:'Virtual Premier',group:'B',round:'Group stage',comment:'Arsenal build an attack down the right.',events:[[12,'home','Reed'],[39,'away','Cole']],possession:51},
 {id:2,home:4,away:5,score:[3,0],minute:90,status:'Finished',league:'Virtual Bundesliga',group:'C',round:'Group stage',comment:'Full time. Bayern keep a clean sheet.',events:[[11,'home','Brandt'],[47,'home','Klein'],[75,'home','Brandt']],possession:64},
 {id:3,home:6,away:7,score:[0,1],minute:81,status:'Live',league:'Virtual Serie A',group:'D',round:'Group stage',comment:'Milan defend a narrow lead.',events:[[59,'away','Rossi']],possession:46},
 {id:4,home:8,away:9,score:[2,2],minute:90,status:'Finished',league:'Virtual Champions',group:'A',round:'Quarter-final',comment:'Full time. The Madrid derby ends level.',events:[[9,'home','Santos'],[31,'away','Vega'],[64,'home','Santos'],[83,'away','Ruiz']],possession:55},
 {id:5,home:10,away:11,score:[2,0],minute:37,status:'Live',league:'Virtual Premier',group:'B',round:'Group stage',comment:'City control possession in midfield.',events:[[14,'home','Miles'],[29,'home','Stone']],possession:62},
 {id:6,home:12,away:13,score:[1,0],minute:90,status:'Finished',league:'Virtual Bundesliga',group:'C',round:'Group stage',comment:'Full time. Leverkusen take three points.',events:[[67,'home','Becker']],possession:54},
 {id:7,home:14,away:15,score:[1,3],minute:90,status:'Finished',league:'Virtual Serie A',group:'D',round:'Group stage',comment:'Full time. Napoli finish strongly.',events:[[16,'away','Marino'],[34,'home','Ricci'],[63,'away','Marino'],[86,'away','Moretti']],possession:44}
];
let view='matches',statusFilter='all',activeId=0,clubId=0,half=1,teamSide='home',group='A',round='all',detailTab='summary';
let followed=new Set([1,4]),toastTimer;
const badge=(id,size='')=>`<span class="club-badge cover-${id%8} ${size}" aria-hidden="true">${clubs[id].short}</span>`;
const score=g=>g.score.join(' : ');
const gameTitle=g=>`${clubs[g.home].name} · ${clubs[g.away].name}`;
const descriptions={matches:['Match centre','Every fixture. Every detail. All in one place.'],favorites:['Watchlist','The fixtures you want to keep close.'],clubs:['Club summary','Form, players and the numbers behind the badge.'],championships:['Championships','Follow groups, knockout rounds and matchdays.'],standings:['League overview','Every result has its place in the table.'],statistics:['Statistics','Compare the patterns behind the scoreline.'],lineups:['Match overview','Two teams. Every player. Every moment.'],profile:['Your profile','Your football workspace, set up for you.'],settings:['Settings','Make the match centre comfortable to read.']};
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function switchView(next){if(!descriptions[next])return;view=next;const [title,desc]=descriptions[view];$('#library-title').innerHTML=`${title}<span class="title-dot">.</span>`;$('#breadcrumb-current').textContent=title;$('#view-description').textContent=desc;$('#mobile-view').value=view;document.querySelectorAll('.sidebar [data-go]').forEach(b=>b.classList.toggle('selected',b.dataset.go===view));const isMatches=['matches','favorites'].includes(view);$('#match-panel').hidden=!isMatches;$('#match-toolbar').hidden=!isMatches;$('#aux-panel').hidden=isMatches;if(!isMatches){$('#filter-panel').hidden=true;$('#filter-button').setAttribute('aria-expanded','false');renderAux()}else renderMatches();fillIcons()}
function renderMatches(){const q=$('#match-search').value.trim().toLowerCase(),league=$('#league-filter').value,date=$('#date-filter').value;const list=games.filter(g=>(view!=='favorites'||followed.has(g.id))&&(statusFilter==='all'||g.status===statusFilter)&&(league==='all'||g.league===league)&&date==='2026-09-22'&&`${gameTitle(g)} ${g.league}`.toLowerCase().includes(q));$('#match-rows').innerHTML=list.map((g,i)=>`<tr class="${activeId===g.id?'active-track':''}"><td class="number-col"><button class="row-play" data-open="${g.id}" aria-label="Open ${gameTitle(g)}">${String(i+1).padStart(2,'0')}</button></td><td><button class="track-info match-row-button" data-open="${g.id}" aria-label="Open ${gameTitle(g)}"><span class="badge-pair">${badge(g.home)}${badge(g.away)}</span><span class="track-copy"><strong>${clubs[g.home].name} <span class="versus">vs</span> ${clubs[g.away].name}</strong><small>${g.status==='Live'?g.minute+'′ · ':''}${g.comment}</small></span></button></td><td class="date-cell">${g.league.replace('Virtual ','V. ')}</td><td class="score-cell">${score(g)}</td><td><span class="visibility-tag ${g.status==='Live'?'public':''}">${g.status==='Live'?g.minute+'′ Live':'FT'}</span></td><td><button class="favorite-button" data-follow="${g.id}" aria-pressed="${followed.has(g.id)}" aria-label="${followed.has(g.id)?'Unfollow':'Follow'} ${gameTitle(g)}">${icon('heart')}</button></td></tr>`).join('');$('.match-table').hidden=!list.length;$('#empty-state').hidden=!!list.length;updateStrip()}
function updateStrip(){const g=games[activeId];$('#selected-cover').className=`cover cover-${g.home%8}`;$('#selected-cover').textContent=clubs[g.home].short;$('#selected-match-title').textContent=gameTitle(g);$('#selected-match-comment').textContent=`${g.status==='Live'?g.minute+'′':'FT'} · ${g.comment}`;$('#selected-minute').textContent=g.status==='Live'?g.minute+'′':'FT';$('#selected-score').textContent=score(g);$('#strip-events').innerHTML=`<i class="timeline-progress" style="width:${g.minute/90*100}%"></i>${g.events.map(e=>`<span class="timeline-goal ${e[1]}" style="left:${e[0]/90*100}%" title="${e[0]}′ ${e[2]}"></span>`).join('')}`;$('#selected-match-button').setAttribute('aria-label',`Open ${gameTitle(g)}`)}
function toggleFollow(id){followed.has(id)?followed.delete(id):followed.add(id);renderMatches();toast(followed.has(id)?'Match added to your watchlist':'Match removed from your watchlist')}
function resetFilters(){statusFilter='all';$('#match-search').value='';$('#league-filter').value='all';$('#date-filter').value='2026-09-22';updateStatusTabs();switchView('matches')}
function updateStatusTabs(){document.querySelectorAll('[data-tab]').forEach(b=>{const selected=b.dataset.tab===statusFilter;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1})}
function chartArea(label='Ball possession',a=58,b=42){const p1='M0 74C35 65 46 22 83 30S135 72 166 46S218 10 250 37S301 72 332 36S391 19 430 39';const p2='M0 42C35 36 50 61 83 68S133 14 166 26S215 71 250 61S295 11 332 22S390 75 430 52';return `<div class="area-chart" role="img" aria-label="${label}: home ${a}%, away ${b}%"><svg viewBox="0 0 430 100" preserveAspectRatio="none"><path d="${p1}V100H0Z" fill="#a855f726"/><path d="${p1}" stroke="#b78ae5" fill="none" stroke-width="2"/><path d="${p2}" stroke="#58bd9c" fill="none" stroke-width="2"/><path d="M0 25H430M0 50H430M0 75H430" stroke="#ffffff09" stroke-dasharray="3 5"/></svg><div class="chart-axis"><span>0′</span><span>15′</span><span>30′</span><span>HT</span><span>60′</span><span>75′</span><span>90′</span></div></div>`}
function donut(c){return `<div class="donut-wrap"><div class="donut" style="background:conic-gradient(#a877da 0 ${c.w*10}%,#58b99b ${c.w*10}% ${(c.w+c.d)*10}%,#53475f ${(c.w+c.d)*10}% 100%)" role="img" aria-label="${c.w} wins, ${c.d} draws, ${c.l} losses"><div><strong>10</strong><small>MATCHES</small></div></div><div class="chart-legend"><span><i class="purple"></i>${c.w} Wins</span><span><i class="emerald"></i>${c.d} Draws</span><span><i class="loss"></i>${c.l} Losses</span></div></div>`}
function radar(g){const home=[g.possession,67,50,65,72,60],away=[100-g.possession,48,73,55,58,69];const point=(i,v)=>{const angle=(i*60-90)*Math.PI/180;return `${130+Math.cos(angle)*v*.82},${104+Math.sin(angle)*v*.82}`};return `<div class="radar-chart" role="img" aria-label="Team comparison of possession, shots, passes, corners, saves and attacks"><svg viewBox="0 0 260 215">${[25,50,75,100].map(v=>`<polygon points="${home.map((_,i)=>point(i,v)).join(' ')}" fill="none" stroke="#ffffff0d"/>`).join('')}${home.map((_,i)=>`<path d="M130 104L${point(i,100)}" stroke="#ffffff0b"/>`).join('')}<polygon points="${home.map((v,i)=>point(i,v)).join(' ')}" fill="#a855f724" stroke="#be90ea" stroke-width="2"/><polygon points="${away.map((v,i)=>point(i,v)).join(' ')}" fill="#10b9810e" stroke="#61bda1" stroke-width="2"/><g fill="#94859f" font-size="10" text-anchor="middle"><text x="130" y="12">POSSESSION</text><text x="220" y="59">SHOTS</text><text x="222" y="157">PASSES</text><text x="130" y="207">CORNERS</text><text x="39" y="157">SAVES</text><text x="39" y="59">ATTACKS</text></g></svg></div>`}
function teamSelector(){return `<label class="compact-select">Match<select id="analysis-match">${games.map(g=>`<option value="${g.id}" ${g.id===activeId?'selected':''}>${gameTitle(g)}</option>`).join('')}</select></label>`}
const playerNames=['Navarro','Costa','Meyer','Duarte','Weber','Santos','Reed','Klein','Silva','Cole','Rossi'];
function lineup(id,compact=false){const nums=[1,2,4,5,3,6,8,10,7,9,11],points=[[50,87],[17,67],[39,71],[62,71],[83,67],[30,47],[69,47],[50,32],[17,17],[50,12],[83,17]];return `<div class="lineup-pitch ${compact?'compact-pitch':''}" role="img" aria-label="${clubs[id].name} 4-3-3 formation"><div class="pitch-centre"></div><div class="penalty top"></div><div class="penalty bottom"></div>${points.map(([x,y],i)=>`<span class="pitch-player" style="left:${x}%;top:${y}%"><b class="cover-${id%8}">${nums[i]}</b><small>${playerNames[(i+id)%11]}</small></span>`).join('')}<span class="formation-label">4 — 3 — 3</span></div>`}
function statBars(g){const pairs=[['Goals',g.score[0],g.score[1]],['Shots',12+g.id,8+g.id%3],['On target',6+g.id%3,3+g.id%2],['Corners',7,4],['Passes',426+g.id*9,358+g.id*7]];return `<div class="stat-bars">${pairs.map(([name,a,b])=>`<div class="stat-comparison"><div><strong>${a}</strong><span>${name}</span><strong>${b}</strong></div><div class="double-bar"><i style="width:${a+b?a/(a+b)*100:50}%"></i><b style="width:${a+b?b/(a+b)*100:50}%"></b></div></div>`).join('')}</div>`}
function timeline(g){return `<div class="full-timeline"><div class="timeline-caption"><strong>${g.status==='Live'?g.minute+'′':'FULL TIME'}</strong><span>${g.comment}</span></div><div class="event-line"><i style="width:${g.minute/90*100}%"></i>${g.events.map(e=>`<button data-goal-minute="${e[0]}" style="left:${e[0]/90*100}%" aria-label="${e[0]} minute goal by ${e[2]}">⚽<small>${e[0]}′</small></button>`).join('')}</div><div class="chart-axis"><span>KICK-OFF</span><span>HALF TIME</span><span>90′</span></div></div>`}
function gameHeader(g){return `<div class="game-header"><div>${badge(g.home,'large')}<strong>${clubs[g.home].name}</strong><small>${clubs[g.home].location}</small></div><div class="game-score"><span class="visibility-tag ${g.status==='Live'?'public':''}">${g.status==='Live'?'LIVE DEMO · '+g.minute+'′':'FULL TIME'}</span><strong>${score(g)}</strong><small>${g.league}</small></div><div>${badge(g.away,'large')}<strong>${clubs[g.away].name}</strong><small>${clubs[g.away].location}</small></div></div>`}
function chipTabs(items,attr,current){return `<div class="chip-tabs">${items.map(([key,label])=>`<button ${attr}="${key}" class="${key===current?'active':''}" aria-pressed="${key===current}">${label}</button>`).join('')}</div>`}
function renderAux(){const el=$('#aux-panel'),g=games[activeId],c=clubs[clubId];
if(view==='statistics'){el.innerHTML=`<div class="panel-top">${teamSelector()}${chipTabs([['1','First half'],['2','Second half']],'data-half',String(half))}</div><div class="metric-strip"><div><small>Possession</small><strong>${g.possession-(half===1?3:0)}<em>%</em></strong></div><div><small>Total attempts</small><strong>${half===1?7:12+g.id}</strong></div><div><small>Pass accuracy</small><strong>${half===1?86:89}<em>%</em></strong></div><div><small>Avg. sprint</small><strong>${half===1?'25.6':'27.8'}<em>km/h</em></strong></div></div><div class="analytics-grid"><article class="data-card"><h3>Team comparison</h3>${radar(g)}<div class="chart-legend"><span><i class="purple"></i>${clubs[g.home].name}</span><span><i class="emerald"></i>${clubs[g.away].name}</span></div></article><article class="data-card"><h3>Match statistics</h3>${statBars(g)}</article><article class="data-card wide"><div class="card-heading"><h3>Ball possession</h3><span>${g.possession}% / ${100-g.possession}%</span></div>${chartArea('Ball possession',g.possession,100-g.possession)}</article><article class="data-card"><h3>Active actions</h3><div class="actions-chart" role="img" aria-label="Active actions by position, half ${half}">${['GK','LB','CB','CB','RB','CM','CM','CAM','LW','RW','ST'].map((p,i)=>`<div><i style="height:${30+(i*19+half*13)%70}%"></i><small>${p}</small></div>`).join('')}</div></article><article class="data-card"><h3>Field presence</h3><div class="heat-pitch" role="img" aria-label="Higher activity in the right attacking channel"><div></div><i></i></div></article></div>`}
else if(view==='clubs'){el.innerHTML=`<div class="club-picker">${clubs.map(x=>`<button data-club="${x.id}" class="${x.id===clubId?'active':''}" aria-label="View ${x.name}">${badge(x.id)}<span>${x.name}</span></button>`).join('')}</div><div class="club-hero data-card"><div>${badge(c.id,'large')}<span><h3>${c.name} VFC</h3><p>${c.location}</p><small>${c.league}</small></span></div><div class="club-wdl"><span><strong>${c.w}</strong>WINS</span><span><strong>${c.d}</strong>DRAWS</span><span><strong>${c.l}</strong>LOSSES</span></div></div><div class="analytics-grid"><article class="data-card"><h3>Recent form</h3>${donut(c)}</article><article class="data-card"><h3>Starting eleven</h3>${lineup(c.id,true)}</article><article class="data-card wide"><div class="card-heading"><h3>Player roster</h3><span>4–3–3 · Virtual squad</span></div><div class="roster">${playerNames.map((n,i)=>`<div><span class="roster-number">${[1,2,4,5,3,6,8,10,7,9,11][i]}</span><span class="avatar a${i%4+1}">${n.slice(0,2).toUpperCase()}</span><strong>${n}</strong><small>${i===0?'Goalkeeper':i<5?'Defender':i<8?'Midfielder':'Forward'}</small></div>`).join('')}</div></article><article class="data-card stadium-info"><h3>Winmix Arena</h3><strong>42,850</strong><p>Virtual attendance</p><small>18.1°C · Clear sky · Demo conditions</small></article><article class="data-card"><h3>Head coach</h3><div class="coach-profile"><span class="avatar a3">AM</span><div><strong>Alex Morgan</strong><small>Virtual squad manager</small></div></div><p>High press · possession play</p><div class="mini-metrics"><span>Formation <b>4–3–3</b></span><span>Club position <b>${[...clubs].filter(x=>x.league===c.league).sort((a,b)=>b.pts-a.pts).findIndex(x=>x.id===c.id)+1}</b></span></div></article></div>`}
else if(view==='standings'){const league=$('#standings-league')?.value||'all';el.innerHTML=`<div class="panel-top"><label class="compact-select">Competition<select id="standings-league"><option value="all">All virtual clubs</option>${[...new Set(clubs.map(c=>c.league))].map(l=>`<option ${l===league?'selected':''}>${l}</option>`).join('')}</select></label><span class="panel-note">DEMO SEASON · 10 MATCHES PLAYED</span></div><div id="standings-body"></div><article class="data-card"><h3>Championship position</h3>${chartArea('Relative club position trend')}</article>`;renderStandings(league)}
else if(view==='championships'){el.innerHTML=`<div class="panel-top"><span class="panel-note">VIRTUAL EUROPEAN CHAMPIONSHIP</span><label class="compact-select">Round<select id="round-select"><option value="all">All rounds</option><option ${round==='Group stage'?'selected':''}>Group stage</option><option ${round==='Quarter-final'?'selected':''}>Quarter-final</option><option ${round==='Semi-final'?'selected':''}>Semi-final</option><option ${round==='Final'?'selected':''}>Final</option></select></label></div>${chipTabs('ABCDEFG'.split('').map(x=>[x,'Group '+x]),'data-group',group)}<div class="matchday-strip"><label>Matchday<input type="date" id="champ-date" value="${$('#date-filter').value}" min="2026-09-01" max="2026-09-30"></label><span>September 2026 · demo schedule</span></div><div class="calendar-days">${[19,20,21,22,23,24,25].map(d=>`<button data-day="${d}" class="${$('#date-filter').value===`2026-09-${d}`?'active':''}"><small>${['SAT','SUN','MON','TUE','WED','THU','FRI'][d-19]}</small><strong>${d}</strong>${d===22?'<i></i>':''}</button>`).join('')}</div><div id="group-fixtures"></div>`;renderGroup()}
else if(view==='lineups'){el.innerHTML=`<div class="panel-top">${teamSelector()}</div>${gameHeader(g)}${timeline(g)}${chipTabs([['home',clubs[g.home].name],['away',clubs[g.away].name]],'data-team',teamSide)}<div class="analytics-grid"><article class="data-card"><h3>Starting line-up</h3>${lineup(g[teamSide])}</article><article class="data-card"><h3>Goals & match events</h3>${eventList(g)}<div class="match-note">Select a timeline marker to inspect a goal.</div></article></div>`}
else if(view==='profile'){el.innerHTML=`<article class="data-card profile-card"><span class="avatar a4">WA</span><h3>Winmix Analyst</h3><p>Budapest, Hungary</p><span class="visibility-tag">DEMO PROFILE</span><div class="metric-strip"><div><small>Following</small><strong>${followed.size}</strong></div><div><small>Competitions</small><strong>4</strong></div><div><small>Matchday</small><strong>22<em>Sep</em></strong></div></div><button class="button secondary" data-go="favorites">Open your watchlist ↗</button></article><article class="data-card"><h3>Your football workspace</h3><p>Keep selected matches close with the heart button. Your demo watchlist lasts for this page session.</p></article>`}
else if(view==='settings'){el.innerHTML=`<article class="data-card settings-card"><h3>Display preferences</h3><div><span><strong>Dashboard contrast</strong><small>Choose the regular or brighter glass surface.</small></span><button class="button secondary" id="settings-theme">${$('.dashboard').classList.contains('dim-theme')?'Brighter':'Original'}</button></div><div><span><strong>Reading direction</strong><small>Change the dashboard layout direction.</small></span><button class="button secondary" id="settings-rtl">${$('.dashboard').dir==='rtl'?'Right to left':'Left to right'}</button></div><div><label for="settings-font"><strong>Text size</strong><small>Make dashboard labels more comfortable.</small></label><input id="settings-font" type="range" min="100" max="120" step="5" value="${$('#font-size').value}"></div><button class="button secondary" id="reset-display">Reset display preferences</button></article><article class="data-card"><h3>About this dataset</h3><p>All fixtures, scores, player names, statistics, attendance and weather are simulated examples. They are not live sporting results. No external feed is connected.</p></article>`}
fillIcons(el);}
function renderStandings(league){const list=clubs.filter(c=>league==='all'||c.league===league).sort((a,b)=>b.pts-a.pts||b.gf-b.ga-(a.gf-a.ga));$('#standings-body').innerHTML=`<table class="standings-table"><thead><tr><th>#</th><th>CLUB</th><th>W</th><th>D</th><th>L</th><th class="goals-column">GF</th><th class="goals-column">GA</th><th>PTS</th></tr></thead><tbody>${list.map((c,i)=>`<tr><td>${i+1}</td><td><button data-club="${c.id}">${badge(c.id)}<strong>${c.name}</strong></button></td><td>${c.w}</td><td>${c.d}</td><td>${c.l}</td><td class="goals-column">${c.gf}</td><td class="goals-column">${c.ga}</td><td class="points">${c.pts}</td></tr>`).join('')}</tbody></table>`}
function renderGroup(){const date=$('#date-filter').value;const list=games.filter(g=>g.group===group&&(round==='all'||g.round===round)&&date==='2026-09-22');$('#group-fixtures').innerHTML=list.length?`<div class="fixture-grid">${list.map(g=>`<button class="fixture-card data-card" data-open="${g.id}"><span>${badge(g.home)}<strong>${clubs[g.home].name}</strong></span><span class="fixture-score">${score(g)}<small>${g.status==='Live'?g.minute+'′ LIVE DEMO':'FULL TIME'}</small></span><span>${badge(g.away)}<strong>${clubs[g.away].name}</strong></span><small>${g.round} · Group ${g.group}</small></button>`).join('')}</div>`:'<div class="empty-state"><strong>No fixtures in this selection</strong><p>The demo includes Groups A–D on 22 September.</p><button class="button secondary" id="reset-schedule">View demo fixtures</button></div>'}
function eventList(g){return `<ol class="event-list">${g.events.map(([minute,side,name])=>`<li data-event="${minute}"><b>${minute}′</b><span>⚽</span><div><strong>${name}</strong><small>${clubs[g[side]].name} · Goal</small></div></li>`).join('')}</ol>`}
function openMatch(id){activeId=id;detailTab='summary';teamSide='home';renderMatches();renderDetail();$('#match-dialog').showModal()}
function renderDetail(){const g=games[activeId];$('#match-dialog-title').textContent=gameTitle(g);$('#match-detail').innerHTML=`${gameHeader(g)}${chipTabs([['summary','Summary'],['lineups','Lineups'],['goals','Goals'],['statistics','Statistics']],'data-detail-tab',detailTab)}<div class="detail-content">${detailTab==='summary'?`${timeline(g)}${statBars(g)}`:detailTab==='lineups'?`${chipTabs([['home',clubs[g.home].name],['away',clubs[g.away].name]],'data-detail-team',teamSide)}${lineup(g[teamSide])}`:detailTab==='goals'?eventList(g):`<div class="analytics-grid"><article class="data-card"><h3>Team comparison</h3>${radar(g)}</article><article class="data-card"><h3>Match statistics</h3>${statBars(g)}</article><article class="data-card wide"><h3>Ball possession</h3>${chartArea('Ball possession',g.possession,100-g.possession)}</article></div>`}</div>`}
function changeTheme(){const dim=$('.dashboard').classList.toggle('dim-theme');$('#theme-toggle').setAttribute('aria-pressed',String(dim));if(view==='settings')renderAux()}
function changeDirection(){const rtl=$('.dashboard').dir!=='rtl';$('.dashboard').dir=rtl?'rtl':'ltr';$('#rtl-toggle').setAttribute('aria-pressed',String(rtl));if(view==='settings')renderAux()}
function changeFont(value){$('#font-size').value=value;$('.dashboard').style.setProperty('--ui-scale',Number(value)/100);if($('#settings-font'))$('#settings-font').value=value}
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a');if(!b)return;
 if(b.dataset.go){switchView(b.dataset.go);return}
 if(b.dataset.open!==undefined){openMatch(Number(b.dataset.open));return}
 if(b.dataset.follow!==undefined){toggleFollow(Number(b.dataset.follow));return}
 if(b.dataset.tab){statusFilter=b.dataset.tab;updateStatusTabs();renderMatches();return}
 if(b.dataset.club!==undefined){clubId=Number(b.dataset.club);switchView('clubs');return}
 if(b.dataset.half){half=Number(b.dataset.half);renderAux();return}
 if(b.dataset.team){teamSide=b.dataset.team;renderAux();return}
 if(b.dataset.detailTab){detailTab=b.dataset.detailTab;renderDetail();return}
 if(b.dataset.detailTeam){teamSide=b.dataset.detailTeam;renderDetail();return}
 if(b.dataset.group){group=b.dataset.group;renderAux();return}
 if(b.dataset.day){$('#date-filter').value=`2026-09-${b.dataset.day}`;renderAux();return}
 if(b.dataset.goalMinute){const goal=games[activeId].events.find(x=>String(x[0])===b.dataset.goalMinute);toast(`${goal[0]}′ — ${goal[2]} scores for ${clubs[games[activeId][goal[1]]].name}`);return}
 if(b.id==='reset-schedule'){group='A';round='all';$('#date-filter').value='2026-09-22';renderAux()}
 if(b.id==='settings-theme')changeTheme();
 if(b.id==='settings-rtl')changeDirection();
 if(b.id==='reset-display'){$('.dashboard').classList.remove('dim-theme');$('.dashboard').dir='ltr';$('#theme-toggle').setAttribute('aria-pressed','false');$('#rtl-toggle').setAttribute('aria-pressed','false');changeFont(100);renderAux()}
});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='analysis-match'){activeId=Number(el.value);teamSide='home';renderAux();updateStrip()}if(el.id==='standings-league')renderStandings(el.value);if(el.id==='round-select'){round=el.value;renderGroup()}if(el.id==='champ-date'){$('#date-filter').value=el.value;renderAux()}});
$('#match-search').addEventListener('input',renderMatches);$('#league-filter').addEventListener('change',renderMatches);$('#date-filter').addEventListener('change',renderMatches);$('#mobile-view').addEventListener('change',e=>switchView(e.target.value));
$('#filter-button').addEventListener('click',()=>{const open=$('#filter-button').getAttribute('aria-expanded')==='true';$('#filter-button').setAttribute('aria-expanded',String(!open));$('#filter-panel').hidden=open});$('#reset-filters').addEventListener('click',resetFilters);$('#empty-reset').addEventListener('click',resetFilters);
$('#selected-match-button').addEventListener('click',()=>openMatch(activeId));$('#next-match').addEventListener('click',()=>{activeId=(activeId+1)%games.length;renderMatches();if(!['matches','favorites'].includes(view))renderAux()});
$('#theme-toggle').addEventListener('click',changeTheme);$('#rtl-toggle').addEventListener('click',changeDirection);$('#font-size').addEventListener('input',e=>changeFont(e.target.value));document.addEventListener('input',e=>{if(e.target.id==='settings-font')changeFont(e.target.value)});
document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')];let i=tabs.indexOf(document.activeElement);i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[i].focus();statusFilter=tabs[i].dataset.tab;updateStatusTabs();renderMatches()});
const menuButton=$('.menu-button');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menuButton.setAttribute('aria-label',open?'Open navigation':'Close navigation');$('.nav-links').classList.toggle('open',!open)});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open navigation');$('.nav-links').classList.remove('open')}));
const tourSteps=[{title:'Every fixture, in focus.',description:'Switch between live and finished demo fixtures. Search for a team, choose a league, and follow a match with the heart button.',visual:`${badge(0,'large')}<span style="font-size:25px">2 : 1</span>${badge(1,'large')}`},{title:'Go beyond the score.',description:'Open any match to explore goals, possession, team comparisons and player formations. Switch teams to see both sides of the pitch.',visual:`<span style="width:100%;max-width:300px">${chartArea()}</span>`},{title:'See the whole competition.',description:'Explore club form, league tables and championship groups from the sidebar. All results are simulated examples; no live data feed is connected.',visual:`<span class="brand-icon" style="width:80px;height:80px;font-size:45px">W</span>`}];
let tourStep=0;
function renderTour(){const s=tourSteps[tourStep];$('#tour-step-label').textContent=`THE WINMIX TOUR · 0${tourStep+1} / 03`;$('#tour-title').textContent=s.title;$('#tour-description').textContent=s.description;$('#tour-visual').innerHTML=s.visual;$('#tour-next').innerHTML=tourStep===2?'Explore the matches <span aria-hidden="true">↗</span>':'Next <span aria-hidden="true">→</span>';document.querySelectorAll('.tour-dots i').forEach((x,i)=>x.classList.toggle('active',i===tourStep))}
function openTour(){tourStep=0;renderTour();$('#tour-dialog').showModal()}
$('#tour-button').addEventListener('click',openTour);$('#tour-library-button').addEventListener('click',openTour);$('#tour-next').addEventListener('click',()=>{if(tourStep===2){$('#tour-dialog').close();resetFilters();$('#library').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('#tab-all').focus({preventScroll:true})}else{tourStep++;renderTour()}});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()})});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();switchView('matches');$('#match-search').focus()}});
$('.activity-bars').innerHTML=Array.from({length:34},(_,i)=>`<i style="height:${8+Math.abs(Math.sin(i*1.7)*Math.cos(i*.37))*29}px"></i>`).join('');$('#feature-momentum').innerHTML=chartArea();
document.querySelector('.feature-card a').dataset.go='statistics';
fillIcons();renderMatches();
if(window.gsap&&window.ScrollTrigger&&!matchMedia('(prefers-reduced-motion: reduce)').matches){gsap.registerPlugin(ScrollTrigger);gsap.from('[data-word]',{yPercent:110,opacity:0,duration:1.1,stagger:.16,ease:'power3.out',delay:.2});gsap.from('[data-hero]',{y:14,opacity:0,duration:.9,stagger:.13,ease:'power2.out',delay:.15});gsap.from('.hero-monogram',{scale:.88,opacity:0,duration:1.3,ease:'power3.out'});gsap.from('.dashboard-shell',{y:38,opacity:0,duration:1.1,ease:'power3.out',delay:.65});gsap.to('[data-float]',{y:10,duration:4.5,repeat:-1,yoyo:true,stagger:1,ease:'sine.inOut'});gsap.from('.feature-card',{scrollTrigger:{trigger:'.feature-grid',start:'top 90%',once:true},y:25,opacity:0,duration:.7,stagger:.12,ease:'power2.out'})}
