import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { pipeline } from 'node:stream/promises';
import { parser } from 'stream-json';
import { pick } from 'stream-json/filters/pick.js';
import { streamArray } from 'stream-json/streamers/stream-array.js';
import { chain } from 'stream-chain';
import parquet from 'parquetjs-lite';

export const EXTRACTOR_VERSION = '1.0.0';
export const DATASET_VERSION = 'winmix-analytical-v1';
const TABLE_SCHEMAS = {
  seasons: { season_id: { type: 'UTF8' }, league: { type: 'UTF8', optional: true }, season_name: { type: 'UTF8', optional: true }, match_count: { type: 'INT64' }, extras: { type: 'UTF8', optional: true } },
  matches: {
    season_id:{type:'UTF8',optional:true}, league:{type:'UTF8',optional:true}, season_name:{type:'UTF8',optional:true}, match_id:{type:'UTF8'}, match_number:{type:'INT64',optional:true}, source_row_index:{type:'INT64'}, source_file_id:{type:'UTF8'}, home_team:{type:'UTF8',optional:true}, away_team:{type:'UTF8',optional:true}, canonical_home_team:{type:'UTF8',optional:true}, canonical_away_team:{type:'UTF8',optional:true}, ht_home:{type:'INT64',optional:true}, ht_away:{type:'INT64',optional:true}, ft_home:{type:'INT64',optional:true}, ft_away:{type:'INT64',optional:true}, total_goals:{type:'INT64',optional:true}, btts:{type:'BOOLEAN',optional:true}, outcome:{type:'UTF8',optional:true}, kickoffIso:{type:'UTF8',optional:true}, date:{type:'UTF8',optional:true}, data_sufficiency:{type:'UTF8',optional:true}, cold_start:{type:'BOOLEAN',optional:true}, confidence:{type:'DOUBLE',optional:true}, confidence_label:{type:'UTF8',optional:true}, decision:{type:'UTF8',optional:true}, recommendation:{type:'UTF8',optional:true}, caveat:{type:'UTF8',optional:true}, extras:{type:'UTF8',optional:true}
  },
  top_scores: { match_id:{type:'UTF8'}, season_id:{type:'UTF8',optional:true}, rank:{type:'INT64'}, score_home:{type:'INT64'}, score_away:{type:'INT64'}, score:{type:'UTF8'}, probability:{type:'DOUBLE',optional:true}, extras:{type:'UTF8',optional:true} },
  calibration: { league:{type:'UTF8',optional:true}, market:{type:'UTF8',optional:true}, probability_band:{type:'UTF8',optional:true}, n:{type:'INT64',optional:true}, hits:{type:'INT64',optional:true}, avg_probability:{type:'DOUBLE',optional:true}, hit_rate:{type:'DOUBLE',optional:true}, gap:{type:'DOUBLE',optional:true}, brier:{type:'DOUBLE',optional:true}, log_loss:{type:'DOUBLE',optional:true}, ece:{type:'DOUBLE',optional:true}, calibrated:{type:'BOOLEAN',optional:true}, temperature:{type:'DOUBLE',optional:true}, extras:{type:'UTF8',optional:true} },
  model_fit: { league:{type:'UTF8',optional:true}, fit_index:{type:'INT64',optional:true}, model_kind:{type:'UTF8',optional:true}, sample_size:{type:'INT64',optional:true}, average_log_loss:{type:'DOUBLE',optional:true}, m1_source:{type:'UTF8',optional:true}, m1_sample_size:{type:'INT64',optional:true}, m1_average_log_loss:{type:'DOUBLE',optional:true}, ensemble_m1_weight:{type:'DOUBLE',optional:true}, ensemble_tuned:{type:'BOOLEAN',optional:true}, model_dimension:{type:'INT64',optional:true}, regularization:{type:'DOUBLE',optional:true}, iterations:{type:'INT64',optional:true}, dixon_coles_rho:{type:'DOUBLE',optional:true}, parameters:{type:'UTF8',optional:true}, extras:{type:'UTF8',optional:true} },
  experiments: { league:{type:'UTF8',optional:true}, experiment:{type:'UTF8',optional:true}, model_kind:{type:'UTF8',optional:true}, sample_size:{type:'INT64',optional:true}, log_loss:{type:'DOUBLE',optional:true}, base_log_loss:{type:'DOUBLE',optional:true}, improvement:{type:'DOUBLE',optional:true}, brier:{type:'DOUBLE',optional:true}, skill_confidence_interval:{type:'UTF8',optional:true}, rho:{type:'DOUBLE',optional:true}, extras:{type:'UTF8',optional:true} }
};
const isObj = v => v && typeof v === 'object' && !Array.isArray(v);
const first = (o, keys) => keys.map(k => o?.[k]).find(v => v !== undefined && v !== null);
const num = v => v === undefined || v === null || v === '' || Number.isNaN(Number(v)) ? undefined : Number(v);
const bool = v => v === undefined || v === null ? undefined : Boolean(v);
const text = v => v === undefined || v === null ? undefined : String(v);
const json = v => v === undefined ? undefined : JSON.stringify(v);
function flattenKnown(row, target) { const out = {}; for (const k of Object.keys(row || {})) if (target[k] === undefined && k !== 'extras') out[k] = row[k]; return out; }
function toRow(schema, row) { const output = {}; for (const [key, spec] of Object.entries(schema)) { let v = row[key]; if (v === undefined || v === null) continue; if (spec.type === 'UTF8') v = typeof v === 'string' ? v : JSON.stringify(v); if (spec.type === 'INT64') v = Number.isFinite(Number(v)) ? Math.trunc(Number(v)) : undefined; if (spec.type === 'DOUBLE') v = Number.isFinite(Number(v)) ? Number(v) : undefined; if (spec.type === 'BOOLEAN') v = Boolean(v); if (v !== undefined) output[key] = v; } return output; }
async function openWriters(outDir) { fs.mkdirSync(outDir,{recursive:true}); const writers={}; for (const [name, fields] of Object.entries(TABLE_SCHEMAS)) writers[name]=await parquet.ParquetWriter.openFile(new parquet.ParquetSchema(fields), path.join(outDir, `${name}.parquet`)); return writers; }
async function closeWriters(writers) { await Promise.all(Object.values(writers).map(w => w.close())); }
function locate(v, names) { if (!isObj(v)) return undefined; for (const n of names) if (v[n] !== undefined) return v[n]; return undefined; }
export async function extract(sourceFile, outputRoot) {
  const source = path.resolve(sourceFile); const stat=fs.statSync(source); const hash=crypto.createHash('sha256'); const sourceFileId=path.basename(source); const out=path.resolve(outputRoot); const analytical=path.join(out,'analytical'); const metadata=path.join(out,'metadata'); const reports=path.join(out,'reports');
  fs.mkdirSync(metadata,{recursive:true}); fs.mkdirSync(reports,{recursive:true}); const writers=await openWriters(analytical);
  const counts={seasons:0,matches:0,top_scores:0,calibration:0,model_fit:0,experiments:0}; const paths=new Map(); const nulls=new Map(); const seasonIds=new Set(); const matchIds=new Set(); const topCounts=new Map(); const issues=[]; let exportTimestamp; let schemaVersion; let sourceRowIndex=0;
  const recordPaths=(obj,prefix='')=>{ if (!isObj(obj)) return; for(const [k,v] of Object.entries(obj)){ const p=prefix?`${prefix}.${k}`:k; paths.set(p,(paths.get(p)||0)+1); if(v===null||v===undefined) nulls.set(p,(nulls.get(p)||0)+1); if(isObj(v)) recordPaths(v,p); } };
  const seasonStream=fs.createReadStream(source); seasonStream.on('data', c=>hash.update(c));
  let root;
  // stream-json emits the root object; Pick isolates seasons without materializing match arrays.
  const seasonParser=chain([fs.createReadStream(source), parser(), pick({filter:'seasons'}), streamArray()]);
  const pending=[];
  seasonParser.on('data', ({value:season})=>{ pending.push((async()=>{ seasonIds.add(String(season.id ?? season.seasonId ?? season.season_id ?? counts.seasons)); counts.seasons++; schemaVersion ??= text(season.schemaVersion); exportTimestamp ??= first(season,['exportTimestamp','exportedAt']); recordPaths(season,'seasons.item'); const sid=String(season.id ?? season.seasonId ?? season.season_id ?? counts.seasons); const matches=Array.isArray(season.matches)?season.matches:[]; await writers.seasons.appendRow(toRow(TABLE_SCHEMAS.seasons,{season_id:sid,league:first(season,['league','leagueId']),season_name:first(season,['name','seasonName']),match_count:matches.length,extras:json(flattenKnown(season,TABLE_SCHEMAS.seasons))})); for(const match of matches){ sourceRowIndex++; recordPaths(match,'seasons.item.matches.item'); const matchId=String(first(match,['id','matchId','match_id']) ?? `${sid}:${sourceRowIndex}`); if(matchIds.has(matchId)) issues.push(`duplicate match id: ${matchId}`); matchIds.add(matchId); const ft=first(match,['ft','fullTime','finalScore']); const ht=first(match,['ht','halfTime','halfTimeScore']); const fh=num(isObj(ft)?first(ft,['home','h']):first(match,['ftHome','homeGoals'])); const fa=num(isObj(ft)?first(ft,['away','a']):first(match,['ftAway','awayGoals'])); const hh=num(isObj(ht)?first(ht,['home','h']):first(match,['htHome'])); const ha=num(isObj(ht)?first(ht,['away','a']):first(match,['htAway'])); const pipeline=first(match,['pipeline','forecast','prediction'])||{}; const probs=first(pipeline,['probabilities','markets','secondaryMarkets'])||{}; const row={season_id:sid,league:first(season,['league','leagueId']),season_name:first(season,['name','seasonName']),match_id:matchId,match_number:num(first(match,['matchNumber','number'])),source_row_index:sourceRowIndex,source_file_id:sourceFileId,home_team:first(match,['homeTeam','home','home_team']),away_team:first(match,['awayTeam','away','away_team']),canonical_home_team:first(match,['canonicalHomeTeam','canonical_home_team']),canonical_away_team:first(match,['canonicalAwayTeam','canonical_away_team']),ht_home:hh,ht_away:ha,ft_home:fh,ft_away:fa,total_goals:fh!==undefined&&fa!==undefined?fh+fa:undefined,btts:fh!==undefined&&fa!==undefined?fh>0&&fa>0:undefined,outcome:fh===undefined||fa===undefined?undefined:fh>fa?'H':fh<fa?'A':'D',kickoffIso:first(match,['kickoffIso']),date:first(match,['date']),data_sufficiency:first(match,['dataSufficiency','data_sufficiency']),cold_start:bool(first(match,['coldStart','cold_start'])),confidence:num(first(pipeline,['confidence'])),confidence_label:first(pipeline,['confidenceLabel','confidence_label']),decision:first(match,['decision'])||first(pipeline,['decision']),recommendation:first(match,['recommendation'])||first(pipeline,['recommendation']),caveat:first(match,['caveat'])||first(pipeline,['caveat'])};
      for(const [k,v] of Object.entries(pipeline)){ if(k==='topScores'||k==='top_scores'||k==='probabilities'||k==='markets'||k==='secondaryMarkets') continue; if(TABLE_SCHEMAS.matches[k]) row[k]=v; } row.extras=json({matchExtras:flattenKnown(match,TABLE_SCHEMAS.matches),pipeline,markets:probs}); await writers.matches.appendRow(toRow(TABLE_SCHEMAS.matches,row)); counts.matches++; const scores=first(pipeline,['topScores','top_scores'])||first(match,['topScores','top_scores'])||[]; topCounts.set(matchId,scores.length); for(let i=0;i<scores.length;i++){const s=scores[i]||{}; const sh=num(first(s,['home','scoreHome','score_home'])); const sa=num(first(s,['away','scoreAway','score_away'])); await writers.top_scores.appendRow(toRow(TABLE_SCHEMAS.top_scores,{match_id:matchId,season_id:sid,rank:num(first(s,['rank']))??i+1,score_home:sh,score_away:sa,score:sh!==undefined&&sa!==undefined?`${sh}-${sa}`:first(s,['score']),probability:num(first(s,['probability','p'])),extras:json(flattenKnown(s,TABLE_SCHEMAS.top_scores))})); counts.top_scores++; }} })()); });
  await new Promise((resolve,reject)=>{seasonParser.on('end',resolve);seasonParser.on('error',reject)}); await Promise.all(pending); await closeWriters(writers); const sourceHash=hash.digest('hex');
  const manifest={source_file:sourceFileId,source_path:source,source_size_bytes:stat.size,source_sha256:sourceHash,schema_version:schemaVersion||'unknown',export_timestamp:exportTimestamp||null,extraction_timestamp:new Date().toISOString(),season_count:counts.seasons,match_count:counts.matches,top_score_count:counts.top_scores,distinct_json_paths:[...paths.keys()].sort(),field_coverage:Object.fromEntries([...paths].sort()),null_coverage:Object.fromEntries([...nulls].sort()),extractor_version:EXTRACTOR_VERSION,dataset_version:DATASET_VERSION,source_to_analytical_table:{seasons:'seasons.parquet',matches:'matches.parquet',top_scores:'top_scores.parquet',calibration:'calibration.parquet',model_fit:'model_fit.parquet',experiments:'experiments.parquet'},row_counts:counts,top_score_counts:Object.fromEntries(topCounts),issues}; fs.writeFileSync(path.join(metadata,'dataset_manifest.json'),JSON.stringify(manifest,null,2)); fs.writeFileSync(path.join(reports,'extraction_report.md'),`# WinMix Extraction Report\n\n- Source: ${sourceFileId}\n- SHA-256: ${sourceHash}\n- Seasons: ${counts.seasons}\n- Matches: ${counts.matches}\n- Top scores: ${counts.top_scores}\n- Extractor: ${EXTRACTOR_VERSION}\n\nUnknown fields are retained in extras; all discovered JSON paths are recorded in the manifest.\n`); return manifest;
}
if (import.meta.url===`file://${process.argv[1]}`) { const input=process.argv[2]||process.env.JSON; const output=process.argv[3]||'analytics-output'; if(!input) throw new Error('Usage: node scripts/analytics/extract.mjs <source.json> [output-dir]'); extract(input,output).then(m=>console.log(JSON.stringify({output,counts:m.row_counts},null,2))).catch(e=>{console.error(e);process.exitCode=1}); }
